all: BroadcastReceiver BroadcastSender
BroadcastReceiver: BroadcastReceiver.c DieWithError.c
	gcc BroadcastReceiver.c DieWithError.c -o BroadcastReceiver
BroadcastSender: BroadcastSender.c DieWithError.c
	gcc BroadcastSender.c DieWithError.c -o BroadcastSender
